name: Pre-commit

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install Bazel
        uses: bazelbuild/setup-bazelisk@v3

      - name: Run pre-commit
        run: uvx pre-commit run --all-files
